CREATE SEQUENCE DAILYINFOIDSEQ;

CREATE TABLE PSTM_DAILYINFO(
	DAILYINFOID NUMBER PRIMARY KEY,
	USERID NUMBER NOT NULL,
	REGDATE DATE NOT NULL,
	EXERCISE VARCHAR2(300) NOT NULL,
	CONSUMEKCAL NUMBER NOT NULL,
	FEEDBACK VARCHAR2(500)
);


