CREATE SEQUENCE DIETIDSEQ;
CREATE TABLE PSTM_DIETINFO(
	DIETID NUMBER PRIMARY KEY,
	DAILYINFOID NUMBER NOT NULL,
	UPLOADING VARCHAR2(100) NOT NULL,
	ORIGINING VARCHAR2(100) NOT NULL,
	RESULT VARCHAR2(30) NOT NULL,
	EATENCOUNT NUMBER NOT NULL
);