DROP SEQUENCE PSTM_EXINFOIDSEQ;
DROP TABLE PSTM_EXINFO;

CREATE SEQUENCE PSTM_EXINFOIDSEQ;

CREATE TABLE PSTM_EXINFO(

	EXINFOID NUMBER PRIMARY KEY NOT NULL,
	DAILYINFOID NUMBER NOT NULL,
	CONTENT VARCHAR2(100) NOT NULL,
	KCAL NUMBER NOT NULL,
	
	CONSTRAINT FK_EXINFO_DAILYINFOID FOREIGN KEY(DAILYINFOID)
	REFERENCES PSTM_DAILYINFO(DAILYINFOID)
);


