CREATE TABLE PSTM_LESSON(
	USERID NUMBER NOT NULL,
	CLASSCONTENT VARCHAR2(20),
	PRICEINFO VARCHAR2(20),
	STDENTID VARCHAR2(100)
);


CREATE TABLE PSTM_CERTIFICATION(
	USERID NUMBER PRIMARY KEY,
	CERTIFIURLMOD VARCHAR2(20),
	CERTIFIURL VARCHAR2(20)
);