CREATE SEQUENCE NCTINFOIDSEQ;
CREATE TABLE PSTM_NCTINFO(
	NCTINFOID NUMBER PRIMARY KEY,
	DIETID NUMBER NOT NULL,
	KCAL NUMBER NOT NULL,
	CARBOHYDRATE NUMBER,
	PROTEIN NUMBER,
	FAT NUMBER,
	NCTETC VARCHAR2(200)
);