DROP SEQUENCE RECEIPTIDSEQ;
DROP TABLE PSTM_RECEIPTINFO;

CREATE SEQUENCE RECEIPTIDSEQ;

--영수증  ID, 구매자 ID, 판매자 ID, 구매일, 시작일, 수강기간, 결제수단, 구매시 가격
CREATE TABLE PSTM_RECEIPTINFO(
	
	RECEIPTID NUMBER PRIMARY KEY,
	USERID NUMBER NOT NULL,
	TRAINERID NUMBER NOT NULL,
	BUYDATE DATE NOT NULL,
	STARTDATE DATE NOT NULL,
	DURATION NUMBER NOT NULL,
	PURCHASETYPE VARCHAR2(20) NOT NULL,
	PRICE NUMBER NOT NULL
	
);
