DROP SEQUENCE REVIEWSEQ;
DROP TABLE MVCBOARD;

CREATE SEQUENCE REVIEWDSEQ;

CREATE TABLE REVIEW{
	REVIEWID NUMBER PRIMARY KEY,
	USERID NUMBER
	REVIEWTITLE VARCHAR2(50)
	REVIEWCONTENT VARCHAR2(500)
	UPLOADIMG VARCHAR2(100)
	ORIGINIMG VARCHAR2(100)
	REGDATE DATE
	TRAINNERRID NUMBER
	};
	INSERT INTO REVIEW
	
	SELECT REVIEWID, USERID, REVIEWTITLE, REVIEWCONTENT, UPLOADIMG, ORIGINIMG, REGDATE, TRINNERID
	FROM REVIEW
	ORDER BY REVIEWID DESC;