DROP TABLE PSTM_USERINFO;

CREATE SEQUENCE PSTM_USERSEQ;

CREATE TABLE PSTM_USERINFO(
	USERID NUMBER PRIMARY KEY,
	USERNAME VARCHAR2(20) NOT NULL,
	PASSWORD VARCHAR2(65) NOT NULL,
	PASSWORD_KEY VARCHAR2(65) NOT NULL,
	PHONE VARCHAR2(15) NOT NULL,
	ADDR VARCHAR2(200) NOT NULL,
	DETAILADDR VARCHAR2(100) NOT NULL,
	USERTYPE VARCHAR2(2) NOT NULL CHECK(USERTYPE IN ('N','T')),
	GENDER VARCHAR2(2) NOT NULL CHECK(GENDER IN ('M','F')),
	HEIGHT NUMBER NOT NULL,
	UPLOADIMG VARCHAR2(100),
	ORIGINIMG VARCHAR2(100),
	CAREER VARCHAR2(2000),
	MYCOMMENT VARCHAR2(1000),
	ADMIT VARCHAR2(2) CHECK(ADMIT IN ('Y','N'))
);

INSERT INTO PSTM_USERINFO VALUES(PSTM_USERSEQ.NEXTVAL, 'TEST', 'TEMP', 'TEMP', '010-0000-0000','서울 어딘가', '??아파트 1동', 'N', 'M', 170, NULL, NULL, NULL, NULL, NULL);


SELECT USERID, USERNAME, PASSWORD, PASSWORD_KEY, PHONE, ADDR, DETAILADDR
, USERTYPE, GENDER, HEIGHT, UPLOADIMG, ORIGINIMG, CAREER, MYCOMMENT, ADMIT FROM PSTM_USERINFO;