DROP SEQUENCE IDSEQ;

DROP TABLE PSTM_EXINFO;

CREATE SEQUENCE IDSEQ;

CREATE TABLE PSTM_EXINFO(
	
	ID NUMBER PRIMARY KEY NOT NULL,
	DAILYINFOID NUMBER NOT NULL,
	CONTENT VARCHAR2(100) NOT NULL,
	KCAL NUMBER NOT NULL

);
