DROP SEQUENCE PSTM_WEIGHTIDSEQ;
DROP TABLE PSTM_WEIGHTINFO;

CREATE SEQUENCE PSTM_WEIGHTIDSEQ;

CREATE TABLE PSTM_WEIGHTINFO(

	WEIGHTID NUMBER PRIMARY KEY NOT NULL,
	USERID NUMBER NOT NULL,
	MEASUREDATE DATE NOT NULL,
	WEIGHT NUMBER NOT NULL,
	
	CONSTRAINT FK_WEIGHTINFO_USERID FOREIGN KEY(USERID)
	REFERENCES PSTM_USERINFO(USERID)
);


