DROP TABLE PSTM_CERTIFICATION;

CREATE TABLE PSTM_CERTIFICATION(
	USERID NUMBER PRIMARY KEY,
	CERTIFIURLMOD VARCHAR2(20),
	CERTIFIURL VARCHAR2(20),
	
	CONSTRAINT FK_CERTIFICATION_USERID FOREIGN KEY(USERID)
	REFERENCES PSTM_USERINFO(USERID)
);