DROP SEQUENCE PSTM_DAILYINFOIDSEQ;
DROP TABLE PSTM_DAILYINFO;

CREATE SEQUENCE PSTM_DAILYINFOIDSEQ;

CREATE TABLE PSTM_DAILYINFO(
	DAILYINFOID NUMBER PRIMARY KEY,
	USERID NUMBER NOT NULL,
	REGDATE DATE NOT NULL,
	EXERCISE VARCHAR2(300) NOT NULL,
	CONSUMEKCAL NUMBER NOT NULL,
	FEEDBACK VARCHAR2(500),
	
	CONSTRAINT FK_DAILYINFO_USERID FOREIGN KEY(USERID)
	REFERENCES PSTM_USERINFO(USERID)
);


