DROP SEQUENCE PSTM_DIETIDSEQ;
DROP TABLE PSTM_DIETINFO;

CREATE SEQUENCE PSTM_DIETIDSEQ;
CREATE TABLE PSTM_DIETINFO(
	DIETID NUMBER PRIMARY KEY,
	DAILYINFOID NUMBER NOT NULL,
	UPLOADIMG VARCHAR2(100) NOT NULL,
	ORIGINIMG VARCHAR2(100) NOT NULL,
	RESULT VARCHAR2(30) NOT NULL,
	EATENCOUNT NUMBER NOT NULL,
	
	CONSTRAINT FK_DIETINFO_DAILYINFOID FOREIGN KEY(DAILYINFOID)
	REFERENCES PSTM_DAILYINFO(DAILYINFOID)
);