DROP TABLE PSTM_LESSON;

CREATE TABLE PSTM_LESSON(
	USERID NUMBER NOT NULL,
	CLASSCONTENT VARCHAR2(20),
	PRICEINFO VARCHAR2(20),
	STUDENTID VARCHAR2(100),
	STUDENTCOUNT NUMBER NOT NULL,
	
	CONSTRAINT FK_LESSON_USERID FOREIGN KEY(USERID)
	REFERENCES PSTM_USERINFO(USERID)
);

INSERT INTO PSTM_LESSON VALUES( 14, 'himam', '30000원/56000원' , '{"8":"66", "6" : "77", "9":"65"}' , 3);

UPDATE PSTM_LESSON SET STUDENTID = '{"23":"2", "6" : "3", "9":"4", "17":"6"}';
UPDATE PSTM_LESSON SET STUDENTCOUNT = 1
WHERE USERID = 18;


		
SELECT * FROM PSTM_LESSON;