DROP SEQUENCE PSTM_NAVERSEQ;
DROP TABLE PSTM_NAVERINFO;
CREATE SEQUENCE PSTM_NAVERSEQ;

CREATE TABLE PSTM_NAVERINFO(
	USERID NUMBER PRIMARY KEY,
	ID VARCHAR2(20) NOT NULL,	
	NAME VARCHAR2(13) NOT NULL,
	USERTYPE VARCHAR2(2) NOT NULL CHECK(USERTYPE IN ('N','T')),
	GENDER VARCHAR2(2) NOT NULL CHECK(GENDER IN ('M','F')),
	HEIGHT NUMBER NOT NULL,
	PROFILE_IMAGE CLOB NOT NULL,
	ADMIT VARCHAR2(2) CHECK(ADMIT IN ('Y','N')),
	SIGNOUT VARCHAR2(2) CHECK(SIGNOUT IN ('Y', 'N')) NOT NULL
);

SELECT USERID, ID, NAME, USERTYPE, GENDER, HEIGHT, PROFILE_IMAGE, ADMIT, SIGNOUT
FROM PSTM_NAVERINFO;