DROP SEQUENCE PSTM_USERSEQ;

DROP TABLE PSTM_USERINFO;

CREATE SEQUENCE PSTM_USERSEQ;

CREATE TABLE PSTM_USERINFO(
	USERID NUMBER PRIMARY KEY,
	ID VARCHAR2(20) NOT NULL,
	PASSWORD VARCHAR2(65) NOT NULL,
	PASSWORD_KEY VARCHAR2(65) NOT NULL,
	NAME VARCHAR2(13) NOT NULL,
	PHONE VARCHAR2(15) NOT NULL,
	ADDR VARCHAR2(200) NOT NULL,
	DETAILADDR VARCHAR2(100) NOT NULL,
	USERTYPE VARCHAR2(2) NOT NULL CHECK(USERTYPE IN ('S','N','F','T')),
	GENDER VARCHAR2(2) NOT NULL CHECK(GENDER IN ('M','F')),
	HEIGHT NUMBER NOT NULL,
	UPLOADIMG VARCHAR2(1000),
	CAREER VARCHAR2(2000),
	MYCOMMENT VARCHAR2(1000),
	ADMIT VARCHAR2(2) CHECK(ADMIT IN ('Y','N')),
	SIGNOUT VARCHAR2(2) CHECK(SIGNOUT IN ('Y', 'N')) NOT NULL
);

INSERT INTO PSTM_USERINFO VALUES(PSTM_USERSEQ.NEXTVAL, 'TEST', 'TEMP', 'TEMP', '대충이름', '010-0000-0000','서울 어딘가', '??아파트 1동', 'N', 'M', 170, NULL, NULL, NULL, NULL, NULL, 'N');

DELETE FROM PSTM_USERINFO WHERE USERID = 24;

SELECT USERID, ID, PASSWORD, PASSWORD_KEY, NAME, PHONE, ADDR, DETAILADDR
, USERTYPE, GENDER, HEIGHT, UPLOADIMG, CAREER, MYCOMMENT, ADMIT, SIGNOUT FROM PSTM_USERINFO
ORDER BY USERID;
